'''
CREATE TABLE `tabla_anuncios` ( `ID` INT NOT NULL AUTO_INCREMENT ,  `NOMBRE` VARCHAR(100) NOT NULL ,  `CATEGORIA` VARCHAR(255) NOT NULL ,  `PRECIO` DECIMAL(6,2) NOT NULL ,  `DESCRIPCION` VARCHAR(300) NOT NULL ,  `ENVIO` VARCHAR(2) NOT NULL ,  `CONTACTO` VARCHAR(255) NOT NULL ,  `EMAIL-VALIDADO` INT NOT NULL ,  PRIMARY KEY  (`ID`)) ENGINE = InnoDB;
CREATE TABLE `tabla_categorias` ( `ID` INT NOT NULL AUTO_INCREMENT ,  `NOMBRE` VARCHAR(50) NOT NULL ,    PRIMARY KEY  (`ID`)) ENGINE = InnoDB;
'''

SQL_REGISTRO_ANUNCIO ="INSERT INTO tabla_anuncios (`ID`, `NOMBRE`, `CATEGORIA`, `PRECIO`, `DESCRIPCION`, `ENVIO`, `CONTACTO`, `EMAIL-VALIDADO`, `CODIGO`) VALUES (NULL, %s, %s, %s, %s, %s, %s,'NO', %s);"

SQL_LISTAR_ANUNCIO = "SELECT TA.ID, TA.NOMBRE, TC.NOMBRE, TA.PRECIO, TA.DESCRIPCION, TA.ENVIO, TA.CONTACTO, TA.`EMAIL-VALIDADO` FROM tabla_anuncios AS TA , tabla_categorias AS TC WHERE TA.`EMAIL-VALIDADO` = 'Si' AND TA.CATEGORIA = TC.ID ORDER BY ID DESC;"

SQL_LISTAR_ANUNCIO_PENDIENTE = "SELECT TA.ID, TA.NOMBRE, TC.NOMBRE, TA.PRECIO, TA.DESCRIPCION, TA.ENVIO, TA.CONTACTO, TA.`EMAIL-VALIDADO` FROM tabla_anuncios AS TA , tabla_categorias AS TC WHERE TA.`EMAIL-VALIDADO` != 'Si' AND TA.CATEGORIA = TC.ID ORDER BY ID DESC;"
SQL_COMPROBAR_CODIGO = "SELECT NOMBRE FROM tabla_anuncios WHERE ID= %s AND CODIGO=%s;"

#actualizamos la tabla, que email validado pase a Si en la fila del id que le demos
SQL_VALIDAR_EMAIL = "UPDATE tabla_anuncios SET `EMAIL-VALIDADO`= 'Si' WHERE ID=%s;"

#Zona Admin
SQL_BORRAR_ANUNCIO = "DELETE FROM tabla_anuncios WHERE ID = %s;"
SQL_OBTENER_ANUNCIO_DB = "SELECT * FROM tabla_anuncios WHERE ID = %s;"
SQL_GUARDAR_ANUNCIO_EDITADO = "UPDATE tabla_anuncios SET NOMBRE= %s, CATEGORIA= %s, PRECIO= %s, DESCRIPCION= %s, ENVIO= %s, CONTACTO= %s WHERE ID = %s;"

#SQL administradores
SQL_COMPORBAR_USUARIO = " SELECT ID FROM tabla_admin WHERE USER = %s AND PASSWD = %s;"


#SQL obtener categorias
SQL_OBTENER_CATEGORIAS = "SELECT * FROM tabla_categorias ORDER BY ID ASC;"

#SQL CHAT
SQL_REGISTRAR_MENSAJES = "INSERT INTO tabla_chat (NOMBRE, MENSAJE) VALUES(%s, %s);"

SQL_OBTENER_MENSAJES = "SELECT * FROM tabla_chat ORDER BY ID DESC;"